# Task 1: Vectors

In [1]:
import numpy as np

In [5]:
ages = np.array([28,27,16,7,9,40])
print(f"datatype of age: {ages.dtype}")
print(f"shape of age array: {ages.shape}")
print(f"dimension of age array: {ages.ndim}")

datatype of age: int64
shape of age array: (6,)
dimension of age array: 1


In [6]:
years_until_retirement = np.array([10,5,4,3,6.7,9])
print(f"average is: {np.average(years_until_retirement)}")

average is: 6.283333333333334


# Task 2: Matrices

In [9]:
sales = np.array([[10,0,20],
         [0,0,100],
         [0,0,0],
         [1,10,100]])
print(f"Shape of sales array: {sales.shape}")
print(f"Total number of elements in sales array: {sales.size}")

Shape of sales array: (4, 3)
Total number of elements in sales array: 12


In [12]:
sales = np.zeros([4,3])
sales

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
sales[2,:] = [10,20,30]
sales

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [10., 20., 30.],
       [ 0.,  0.,  0.]])

# Task 3: Addition & Subtraction

In [65]:
marks_term1 = np.array([[90,90,90],
                       [98,98,98],
                       [100,100,100]])
marks_term2 = np.array([[95,95,95],
                       [98,98,98],
                       [95,95,95]])
combined_marks = marks_term1 + marks_term2
improved_marks = marks_term2 - marks_term1

improved_marks

array([[ 5,  5,  5],
       [ 0,  0,  0],
       [-5, -5, -5]])

In [67]:
total_improvement = improved_marks.sum(axis=1)
print(total_improvement)

[ 15   0 -15]


In [69]:
print(f"student who improved highest is student at position: {np.argmax(total_improvement) + 1}")

student who improved highest is student at position: 1


# Task 4: Dot Product

In [71]:
prices = np.array([50,50,100,200])
items = np.array([1,5,2,2])

bill = np.dot(prices,items)
bill

np.int64(900)

In [72]:
prices = np.array([50,50,100,200])
qnty = np.array([[3,4,6,0],[9,6,9,10]])
bill = np.dot(prices,qnty)

ValueError: shapes (4,) and (2,4) not aligned: 4 (dim 0) != 2 (dim 0)

conditions for dot product: 

   - for one dimensional vector: both arrays must have the same number of elements.

   - for two dimensional vector: The columns of the first array must match the rows of the second array.      ( rows, columns ) dot ( rows, columns )  

# Task 5: Reshaping

In [58]:
hours_studied = np.array([19,21,22,24,20,19.5,17,16,0,2,7,8])
hours_studied_reshaped_01 = hours_studied.reshape(3,4)
hours_studied_reshaped_01


array([[19. , 21. , 22. , 24. ],
       [20. , 19.5, 17. , 16. ],
       [ 0. ,  2. ,  7. ,  8. ]])

In [59]:
hours_studied_reshped_02 = hours_studied.reshape(2,6)
hours_studied_reshped_02

array([[19. , 21. , 22. , 24. , 20. , 19.5],
       [17. , 16. ,  0. ,  2. ,  7. ,  8. ]])

In [60]:
hours_studied_reshped_03 = hours_studied.reshape(6,6)

ValueError: cannot reshape array of size 12 into shape (6,6)

# Task 6: Indexing

In [47]:
matrix = np.random.randint(1,51,size = (5,5))
print(matrix)
print("printing the element in the 3rd row and 4th column", matrix[3,4])

[[ 7 21  9 39 18]
 [ 4 25 14 50  9]
 [26  2 20 28 47]
 [ 7 44  8 47 35]
 [14 17 36 50 40]]
printing the element in the 3rd row and 4th column 35


In [48]:
print("printing the last row and the last column ", matrix[-1,-1])

printing the last row and the last column  40


In [49]:
matrix[0,0] = 999
matrix

array([[999,  21,   9,  39,  18],
       [  4,  25,  14,  50,   9],
       [ 26,   2,  20,  28,  47],
       [  7,  44,   8,  47,  35],
       [ 14,  17,  36,  50,  40]], dtype=int32)

# Task 7: Slicing

In [40]:
matrix = np.arange(1,37).reshape(6,6)
matrix

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [41]:
top_left = matrix[:3,:3]
top_left

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15]])

In [44]:
alternate_element = matrix[::2,::2]
alternate_element

array([[ 1,  3,  5],
       [13, 15, 17],
       [25, 27, 29]])

In [45]:
last_elements = matrix[-2:,-2:]
last_elements

array([[29, 30],
       [35, 36]])

# Task 8: Random Matrices

In [38]:
np.random.seed(42)
decimal_value = np.random.rand(3,3)
print(decimal_value)

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


In [35]:
integer_matrix = np.random.randint(10,101,size = (3,3))
print(integer_matrix)

[[33 12 31]
 [62 11 97]
 [39 47 11]]


In [37]:
normal_matrix = np.random.randn(4,4)
normal_matrix

array([[-1.15099358,  0.37569802, -0.60063869, -0.29169375],
       [-0.60170661,  1.85227818, -0.01349722, -1.05771093],
       [ 0.82254491, -1.22084365,  0.2088636 , -1.95967012],
       [-1.32818605,  0.19686124,  0.73846658,  0.17136828]])

Both values are same because we have used seed

# Task 9: Transpose

In [24]:
employees_performance = np.array([[10,100,20,40,50],[40,50,60,70,80],[90,50,40,50,60]])
employees_performance

array([[ 10, 100,  20,  40,  50],
       [ 40,  50,  60,  70,  80],
       [ 90,  50,  40,  50,  60]])

In [25]:
employees_performance.shape

(3, 5)

In [26]:
employees_performance_single_trnspose = np.transpose(employees_performance)
employees_performance_single_trnspose.shape

(5, 3)

In [27]:
employees_performance_double_trnspose = np.transpose(employees_performance_single_trnspose)
employees_performance_double_trnspose.shape

(3, 5)

In [29]:
if(employees_performance.shape == employees_performance_double_trnspose.shape):
        print("transposing the matrix twice gives back the original matrix verified")
else:
        print("transposing the matrix twice doesn't gives back the original matrix verified")

transposing the matrix twice gives back the original matrix verified


In [32]:
matrix_1 = np.random.rand(4,2)
matrix_2 = np.random.rand(3,2)

In [33]:
dot_prod = np.dot(matrix_1,np.transpose(matrix_2))
print(dot_prod)

[[1.00404362 1.04315448 1.22713407]
 [0.56915905 0.74385763 0.83328442]
 [0.58315114 0.84416325 0.92779507]
 [0.36552392 0.6116478  0.65602671]]
